version: '3.5'

services:
   ipfsA:
     image: ipfs/go-ipfs
     container_name: "ipfsA"
     ports:
       - 4001:4001
       - 5001:5001
     configs:
       - source: swarm
         target: /data/ipfs/
     deploy:
       placement:
        constraints:
        - node.labels.peer1==true

   clusterA:
     image: ipfs/ipfs-cluster:latest
     container_name: "ipfs-cluster-A"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfsA/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
       IPFS_BOOTSTRAP_RM_ALL: "true"
     ports:
       - 7094:9094
     depends_on:
       - ipfsA 
     volumes:
       - ./clusterA:/data/ipfs-cluster
     deploy:
       placement:
        constraints:
        - node.labels.peer1==true

   ipfsB:
     image: ipfs/go-ipfs
     container_name: "ipfsB"
     ports:
       - 6001:4001
       - 7001:5001
     configs:
       - source: swarm
         target: /data/ipfs/
     deploy:
       placement:
        constraints:
        - node.labels.peer2==true

   clusterB:
     image: ipfs/ipfs-cluster:latest
     container_name: "ipfs-cluster-B"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfsB/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
       IPFS_BOOTSTRAP_RM_ALL: "true"
     ports:
       - 8094:9094
     depends_on:
       - ipfsB
     volumes:
       - ./clusterB:/data/ipfs-cluster

     deploy:
       placement:
        constraints:
        - node.labels.peer2==true
   ipfsC:
     image: ipfs/go-ipfs
     container_name: "ipfsC"
     ports:
       - 8001:4001
       - 9001:5001
     configs:
       - source: swarm
         target: /data/ipfs/
     deploy:
       placement:
        constraints:
        - node.labels.peer3==true
   clusterC:
     image: ipfs/ipfs-cluster:latest
     container_name: "ipfs-cluster-C"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfsC/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
       IPFS_BOOTSTRAP_RM_ALL: "true"
     ports:
       - 9097:9094
     depends_on:
       - ipfsC
     volumes:
       - ./clusterC:/data/ipfs-cluster
     deploy:
       placement:
        constraints:
        - node.labels.peer3==true

configs:
  swarm:
    external: true
